name: Linter

on:
  push:
    branches:
      - feature/linterprojet

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Lint JavaScript
      run: |
        python linter.py
      working-directory: path/to/your/project


